use_wandb: False
dataset:
    name: 'dataset'
    records_path: null
    initial_dataset: ''
    label_schema: ["Yes", "No"]
    max_samples: 50
    semantic_sampling: False # Change to True in case you don't have M1. Currently there is an issue with faiss and M1

annotator:
    # Use dummy annotator since annotations already exist in the dataset
    method: 'dummy'
    config: {}

predictor:
    method : 'llm'
    config:
        llm:
            type: 'OpenAI'
            name: 'gpt-5-mini'
#            async_params:
#                retry_interval: 10
#                max_retries: 2
            seed: 220
        num_workers: 10
        prompt: 'prompts/predictor_completion/prediction.prompt'
        mini_batch_size: 200  #change to >1 if you want to include multiple samples in the one prompt
        mode: 'prediction'

meta_prompts:
    folder: 'prompts/meta_prompts_classification'
    num_err_prompt: 3  # Number of error examples per sample in the prompt generation
    num_err_samples: 0 # Number of error examples per sample in the sample generation
    history_length: 4 # Number of sample in the meta-prompt history
    num_generated_samples: 0 # Number of generated samples at each iteration
    num_initialize_samples: 0 # Number of generated samples at iteration 0, in zero-shot case
    samples_generation_batch: 1 # Number of samples generated in one call to the LLM
    num_workers: 1 #Number of parallel workers
    warmup: 4 # Number of warmup steps

eval:
    function_name: 'accuracy'
    num_large_errors: 3
    num_boundary_predictions : 0
    error_threshold: 0.5

llm:
    name: 'gpt-5' # This is the meta-prompt LLM, it should be a strong model. For example, using GPT-3.5 will cause an error in many cases.
    type: 'OpenAI' # Can be OpenAI, Anthropic, Google, Azure
    temperature: 0.8

stop_criteria:
    max_usage: 1 #In $ in case of OpenAI models, otherwise number of tokens
    patience: 3 # Number of patience steps
    min_delta: 0.01 # Delta for the improvement definition
